#!/usr/bin/env bash
#install nginx server
STRING="Hello World!"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "$STRING" > /var/www/html/index.nginx-debian.html
service nginx restart
